language: bash

sudo: required

services:
- docker

env:
  global:
    - secure: "HWlbQcEA10vLCJTU43mufu8FGKrjXZViulhjcNZiSQjabzoCcdCcAS7h3LsE0muIQyan8pj8q/Er6zuNVyjjPz3SdGd8qbLvRMbrZwAcdiAzthPicBx766gchcNOxOAETi9ZjPkTjFEYHQbsdaNSzXboA6oThXq8jEFbFKz6P54FIcX2ppWHa+nic99y5YVzhyvzCtTvRvePAEL0W0CxYpcdEui58UN4qSZTAMmOuPpa+ZqjS8L3di69YNH4GJy7u2D6zJn7un3kKRYtbx3TbsCl3jWGZ+yXFE6Q8X5VI41f0p5JOStET67t3/Z3pInzDqPU2M6Mp9826tY0h0vAAJtTfOvW6SVZti68+JoPjIHYHQe6sE9YwdXo9pVDROjMcbzUbflJn8UPjeOJ0scb2n/Q/T/a+CAaSaB3U9p6T7VQpt89dSGU6/YiJToUqcRxZqkQKiI4iNFqapGuMYT/xODpCDVSRFT0T+dM+r2EQrt675SNYMR78uiVMn/KEMtjOmHJ4THPTJm1Q+70Ij6ZVsryWXyRkbdOz1limvIR8FOpu4rcM49LnvkXtOk6uwbQR4kGBhL33YzpUdnYfB7gZleC7CozJtszQ5IZzJpynkXJF2Z0oiV3AhOqrL3HTswj/mlCtuLaRYcQtYhC/hw5vesNErOxJ+FDynaQjsCkVns="
    - secure: "dspzEw7q/gq1a5AcMwsalhoyyP51t1PAAc0tht2woT6vc7aPVyk+sHuXzDjfbbEcU81vc/SDo5198AeiAm2wzSClBSxcRwxOKX5OAYAVbHvd41rntD4NaMyxQQmWbS+MZpJwcExW8SG9LRbZDDwZ8MEHLufDllYkqwvAHBU8FcjWxWj+U50RNbqI6yjGcLMW2fzEwwkNozTO7qotdpNes+SRuxMyBN2KPvg744dYa2TziiEZ2c2Zmu8Lka9mGPxLQ/sPL6IRQiUsJG5oe0VQ4j0AuV3PpcBj7Dqd+Frd9c2mAL/5cCK1C3swNJMTbXXHSV6fcbcBLMSqI+vYjhEnBdtBFW4IzkX87eF7sLArD1YydlPk6gle6rdlSkzfEuu32tvi8F1dPBSBU3T9ALMMo4AjCEj9M5VyG3umntejUtkmyXkQU6ywWF1SsXjf7RriQ6Ry4Ro+LWoxh/OvQCqrlYqOjFUORw3B99BimAv0K3xtRCCeHWWXzIlMQs9XBJIcQAFoflrphDDM5eI0HEDZmgIlVk/m+SOItRIgtPvzDCX3uFHsAp5nctPiYm9SP01QDVlcK5Y88L/5SvA5EkEN/vxbB19zPXaJWMUQHedJ5wIKdW3P3lucr8BzjPtl6F6gS9vPBr8Ublalp9ueH5Tb9JNdkBm8wYkVolSn4Pwu4Nc="
    - secure: "pryg3X5n1e7aVVwhKjKP8KhJ8rNXL8UwLtKs9rTiRHk0nI8NQmQsmF7X60VmT1YXyibcCWOYhrOJ/v7Shv5xERoMSJ6CVk3C+sOlSSS1Tr6m9xo7OoKxkB+bw3sdZBC7nBhbUDEPRvXRXEN+DZCVbdtT6UpSdbhLuQa7u4i6ceH6jn8W/Lkm3tx+euVBRNsbO4WvIKCq602/acFuwiUccFwemwrrSEjUogZaOKIxIAKV7c86OqJrGRjRziAbvBxZTiGm+3z6PxlR9crqoV/AMhAeqgsblGAYIG8v6OMDQ0+jgSgWsouT2bGJ0rhLWblEwYHa0GoU9pl5kvmTvPF6ifadXph2bV2CIm5BE0YBFth0GREpVdAZ4hraLMIJcwyUdySrqy2iq7G8EEaPi1OmIC7VsNFPmRkbcqcnKTlSmeieqUikoC5uOtAemKcsnjAIWQ71R6rKG23/T9GGKRHIyBxvvWxnKbDIynqEQzTqXqfFm+KwZTNyfuAVEbA+3EinblgSmJ2Vb7EXzDhFvlknHWZel+hWYuvvKMNXdftCwyhJg5VX+jR6Wxv1THfis1ZqqI8SOqKnie2XIBSEYRYYLwYog2K8ZBzIra8PqiXGPFfFm2GRySC9foJv4f93CM231PfsVPg56l2eWkHzLPx0Pf6XcCwapIOcvhzvnfqvaYs="
    - PROJECT="hubot"
    - REPOSITORY="encodeering"
  matrix:
    - BASE="alpine" ARCH="amd64" VERSION="2.19" PIN="2.19.0"
    - BASE="alpine" ARCH="armhf" VERSION="2.19" PIN="2.19.0"

install:
- bash <(curl https://raw.githubusercontent.com/encodeering/docker-ci/master/install.sh) 0.1.8

before_script:
- sudo -E bash ./module.sh "." "./setup.sh"

script:
- sudo -E bash ./module.sh "modules" "./build.sh"

after_script:
- docker images

deploy:
  script: sudo -E bash ./module.sh "." "./release.sh"
  provider: script
  skip_cleanup: true
  on:
    all_branches: true
